In [ ]:
from google.colab import drive
drive.mount("/content/drive")

Mounted at /content/drive

In [ ]:
import pandas as pd

In [ ]:
reviews_df = pd.read_csv("/content/drive/MyDrive/BigDataAndDataMiningCoursework/Coursework_dataset/reviews.csv")

In [ ]:
reviews_df.head()

,review_id,order_id,product_id,review_score,review_date,review_text,review_length_chars
0,rev_000001,ord_200369,prod_01620,3.0,1/6/2024,Average quality. The Non-Stick Cookware Set 20...,214
1,rev_000002,ord_306978,prod_01067,4.0,12/19/2023,Amazing product! Better than expected. The bui...,146
2,rev_000003,ord_078396,prod_04954,5.0,10/29/2022,Fantastic purchase. The quality exceeds the pr...,213
3,rev_000004,ord_231351,prod_00296,4.0,4/26/2022,Perfect for my needs. Easy to use and great qu...,185
4,rev_000005,ord_244947,prod_02596,5.0,12/2/2021,Amazing product! Better than expected. The bui...,149

In [ ]:
reviews_df.isnull().sum()

review_id                 0
order_id                  0
product_id                0
review_score           3000
review_date               0
review_text               0
review_length_chars       0
dtype: int64

In [ ]:
duplicated_reviews = reviews_df[reviews_df["review_id"].duplicated(keep=False)]
duplicated_reviews.sort_values("review_id")

Empty DataFrame
Columns: [review_id, order_id, product_id, review_score, review_date, review_text, review_length_chars]
Index: []

In [ ]:
reviews_df.shape

(280000, 7)

In [ ]:
reviews_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 280000 entries, 0 to 279999
Data columns (total 7 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   review_id            280000 non-null  object
 1   order_id             280000 non-null  object
 2   product_id           280000 non-null  object
 3   review_score         277000 non-null  float64
 4   review_date          280000 non-null  object
 5   review_text          280000 non-null  object
 6   review_length_chars  280000 non-null  int64
dtypes: float64(1), int64(1), object(5)
memory usage: 15.0+ MB

In [ ]:
missing_scores = reviews_df.loc[reviews_df["review_score"].isnull(), "review_text"]

missing_scores

71        Excellent quality for the price. Fast delivery...
87        Very happy with this purchase. The Bookshelf W...
166       Good value for money. The Phone Grip Stand 202...
243       Amazing product! Better than expected. The bui...
315       Excellent quality for the price. Fast delivery...
                                ...
279341    Amazing product! Better than expected. The bui...
279643    Outstanding quality! This is my second purchas...
279703    Great product! Exactly what I was looking for....
279883    Received the product in good condition. It wor...
279899    Average quality. The Hot Water Bottle One work...
Name: review_text, Length: 3000, dtype: object

In [ ]:
reviews_df["review_score"] = reviews_df["review_score"].fillna(0)

In [ ]:
reviews_df.isnull().sum()

review_id              0
order_id               0
product_id             0
review_score           0
review_date            0
review_text            0
review_length_chars    0
dtype: int64

In [ ]:
reviews_df.duplicated().sum()

np.int64(0)

In [ ]:
missing_scores = reviews_df.loc[reviews_df["review_score"].isnull(), "review_text"]

missing_scores

Series([], Name: review_text, dtype: object)

In [ ]:
reviews_df

,review_id,order_id,product_id,review_score,review_date,review_text,review_length_chars
0,rev_000001,ord_200369,prod_01620,3.0,1/6/2024,Average quality. The Non-Stick Cookware Set 20...,214
1,rev_000002,ord_306978,prod_01067,4.0,12/19/2023,Amazing product! Better than expected. The bui...,146
2,rev_000003,ord_078396,prod_04954,5.0,10/29/2022,Fantastic purchase. The quality exceeds the pr...,213
3,rev_000004,ord_231351,prod_00296,4.0,4/26/2022,Perfect for my needs. Easy to use and great qu...,185
4,rev_000005,ord_244947,prod_02596,5.0,12/2/2021,Amazing product! Better than expected. The bui...,149
...,...,...,...,...,...,...,...
279995,rev_279996,ord_093495,prod_02854,4.0,10/18/2023,Very happy with this purchase. The Bike Lock H...,230
279996,rev_279997,ord_110149,prod_02382,5.0,9/7/2023,Amazing product! Better than expected. The bui...,114
279997,rev_279998,ord_037944,prod_00425,3.0,1/31/2020,It is an okay product. Not great not terrible....,194
279998,rev_279999,ord_206527,prod_04188,3.0,5/17/2023,It is an okay product. Not great not terrible....,115
279999,rev_280000,ord_384164,prod_01594,3.0,1/5/2024,The product is fine for everyday use. Some min...,173

In [ ]:
reviews_df["review_date"] = pd.to_datetime(reviews_df["review_date"], errors='coerce')

In [ ]:
reviews_df

,review_id,order_id,product_id,review_score,review_date,review_text,review_length_chars
0,rev_000001,ord_200369,prod_01620,3.0,2024-01-06,Average quality. The Non-Stick Cookware Set 20...,214
1,rev_000002,ord_306978,prod_01067,4.0,2023-12-19,Amazing product! Better than expected. The bui...,146
2,rev_000003,ord_078396,prod_04954,5.0,2022-10-29,Fantastic purchase. The quality exceeds the pr...,213
3,rev_000004,ord_231351,prod_00296,4.0,2022-04-26,Perfect for my needs. Easy to use and great qu...,185
4,rev_000005,ord_244947,prod_02596,5.0,2021-12-02,Amazing product! Better than expected. The bui...,149
...,...,...,...,...,...,...,...
279995,rev_279996,ord_093495,prod_02854,4.0,2023-10-18,Very happy with this purchase. The Bike Lock H...,230
279996,rev_279997,ord_110149,prod_02382,5.0,2023-09-07,Amazing product! Better than expected. The bui...,114
279997,rev_279998,ord_037944,prod_00425,3.0,2020-01-31,It is an okay product. Not great not terrible....,194
279998,rev_279999,ord_206527,prod_04188,3.0,2023-05-17,It is an okay product. Not great not terrible....,115
279999,rev_280000,ord_384164,prod_01594,3.0,2024-01-05,The product is fine for everyday use. Some min...,173

In [ ]:
reviews_df["review_score"].dtype

dtype('float64')

In [ ]:
unique_scores = set(reviews_df["review_score"])
unique_scores

{0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0}

In [ ]:
reviews_df["review_score"].value_counts()

review_score
4.0    89007
5.0    83775
3.0    49581
2.0    31765
1.0    22272
0.0     3000
6.0      600
Name: count, dtype: int64

In [ ]:
reviews_df["review_score"] = reviews_df["review_score"].replace(6.0, 5.0)

In [ ]:
unique_scores = set(reviews_df["review_score"])
unique_scores

{0.0, 1.0, 2.0, 3.0, 4.0, 5.0}

In [ ]:
reviews_df["review_score"].value_counts()

review_score
4.0    89007
5.0    84375
3.0    49581
2.0    31765
1.0    22272
0.0     3000
Name: count, dtype: int64

In [ ]:
reviews_df["review_score"]=reviews_df["review_score"].astype(int)

In [ ]:
reviews_df

,review_id,order_id,product_id,review_score,review_date,review_text,review_length_chars
0,rev_000001,ord_200369,prod_01620,3,2024-01-06,Average quality. The Non-Stick Cookware Set 20...,214
1,rev_000002,ord_306978,prod_01067,4,2023-12-19,Amazing product! Better than expected. The bui...,146
2,rev_000003,ord_078396,prod_04954,5,2022-10-29,Fantastic purchase. The quality exceeds the pr...,213
3,rev_000004,ord_231351,prod_00296,4,2022-04-26,Perfect for my needs. Easy to use and great qu...,185
4,rev_000005,ord_244947,prod_02596,5,2021-12-02,Amazing product! Better than expected. The bui...,149
...,...,...,...,...,...,...,...
279995,rev_279996,ord_093495,prod_02854,4,2023-10-18,Very happy with this purchase. The Bike Lock H...,230
279996,rev_279997,ord_110149,prod_02382,5,2023-09-07,Amazing product! Better than expected. The bui...,114
279997,rev_279998,ord_037944,prod_00425,3,2020-01-31,It is an okay product. Not great not terrible....,194
279998,rev_279999,ord_206527,prod_04188,3,2023-05-17,It is an okay product. Not great not terrible....,115
279999,rev_280000,ord_384164,prod_01594,3,2024-01-05,The product is fine for everyday use. Some min...,173

In [ ]:
reviews_df.isnull().sum()

review_id              0
order_id               0
product_id             0
review_score           0
review_date            0
review_text            0
review_length_chars    0
dtype: int64

In [ ]:
reviews_df.dtypes

review_id                      object
order_id                       object
product_id                     object
review_score                    int64
review_date            datetime64[ns]
review_text                    object
review_length_chars             int64
dtype: object

In [ ]:
reviews_df.to_csv('reviews.csv', index=False)